# Generated by Django 6.0.1 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='estatedocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['name'], 'verbose_name_plural': 'Insurance Companies'},
        ),
        migrations.AlterModelOptions(
            name='policyrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ghana_card_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='policy_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['ghana_card_number', 'phone_number'], name='vault_custo_ghana_c_44da5f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_name', 'last_name'], name='vault_custo_first_n_7d378b_idx'),
        ),
    ]
