# Generated by Django 6.0.1 on 2026-08-21 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_assetrecord_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimantAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_email', models.EmailField(max_length=254)),
                ('payment_reference', models.CharField(db_index=True, max_length=150, unique=True)),
                ('access_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('claimant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_vault_grants', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_grants', to='vault.policyrecord')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_claimant_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
