# Generated by Django 6.0.1 on 2026-08-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_claimantaccessgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='claimant_ghana_card',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='claimant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='claimant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='relationship_to_deceased',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
