# Generated by Django 6.0.1 on 2026-08-22 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_claimantaccessgrant_claimant_ghana_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='monthly_premium',
            field=models.DecimalField(decimal_places=2, default=250.0, help_text='Regular recurring premium obligation (GHS)', max_digits=12),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('QUARTERLY', 'Quarterly Contribution'), ('ANNUALLY', 'Annual Contribution'), ('ONE_TIME', 'Single Lump Sum')], default='MONTHLY', max_length=30),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='policy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='policy_status',
            field=models.CharField(choices=[('ACTIVE', 'Active & Current'), ('GRACE_PERIOD', 'In Grace Period'), ('CLAIM_IN_PROGRESS', 'Claim In Progress'), ('SETTLED', 'Fully Settled / Claim Paid'), ('LAPSED', 'Lapsed / Inactive')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='sum_assured',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Guaranteed statutory payout benefit (GHS)', max_digits=14),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='total_premiums_paid',
            field=models.DecimalField(decimal_places=2, default=6400.0, help_text='Cumulative contributions paid by policyholder to date (GHS)', max_digits=14),
        ),
        migrations.CreateModel(
            name='PolicyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('claim_type', models.CharField(choices=[('DEATH_BENEFIT', 'Death Benefit / Next-of-Kin Payout'), ('SURVIVOR_SETTLEMENT', 'Survivor Legacy Transfer'), ('CRITICAL_ILLNESS', 'Critical Care Support Payout'), ('MATURITY_DISBURSEMENT', 'Maturity Liquidation')], default='DEATH_BENEFIT', max_length=30)),
                ('claimant_filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Under Desk Review'), ('DOCS_VERIFIED', 'Statutory Documents Verified'), ('APPROVED', 'Claim Approved for Settlement'), ('DISBURSED', 'Funds Disbursed to Claimant'), ('REJECTED', 'Claim Declined / Ineligible')], default='PENDING_REVIEW', max_length=30)),
                ('filing_date', models.DateField(auto_now_add=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('insurer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='vault.policyrecord')),
            ],
            options={
                'ordering': ['-filing_date', '-created_at'],
            },
        ),
    ]
