# Generated by Django 6.0.1 on 2026-08-26 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_policyrecord_maturity_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=255)),
                ('relationship_stated', models.CharField(max_length=100)),
                ('claimant_phone', models.CharField(max_length=20)),
                ('claimant_ghana_card', models.CharField(max_length=30)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('VERIFIED_MATCH', 'Verified Next-of-Kin Match'), ('UNMATCHED_FLAGGED', 'Unmatched Identity - Audit Flagged'), ('INVESTIGATION_PENDING', 'Under Desk Fraud Review')], default='UNMATCHED_FLAGGED', max_length=30)),
                ('disclaimer_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_logs', to='vault.policyrecord')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim Security & Forensic Audit Log',
                'verbose_name_plural': 'Claim Security & Forensic Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
