# Generated by Django 6.0.1 on 2026-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_claimsecurityauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='camera_permission_granted',
            field=models.BooleanField(default=True, help_text='Records whether the claimant allowed hardware camera verification'),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='claimant_biometric_photo',
            field=models.ImageField(blank=True, help_text='Facial verification snapshot captured via claimant camera during intake', null=True, upload_to='security_audits/biometrics/%Y/%m/'),
        ),
    ]
