# Generated by Django 6.0.1 on 2026-08-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_claimsecurityauditlog_camera_permission_granted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsecurityauditlog',
            name='claimant_biometric_photo',
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='biometric_consent_granted',
            field=models.BooleanField(default=True, help_text='Records statutory consent granted for 3-angle biometric capture'),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='biometric_front_photo',
            field=models.ImageField(blank=True, help_text='Straight-angle facial verification snapshot', null=True, upload_to='security_audits/biometrics/front/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='biometric_left_photo',
            field=models.ImageField(blank=True, help_text='Left profile facial verification snapshot', null=True, upload_to='security_audits/biometrics/left/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='biometric_right_photo',
            field=models.ImageField(blank=True, help_text='Right profile facial verification snapshot', null=True, upload_to='security_audits/biometrics/right/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='camera_permission_granted',
            field=models.BooleanField(default=True, help_text='Records whether hardware camera permission was allowed'),
        ),
    ]
