# Generated by Django 6.0.1 on 2026-09-02 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_claimsecurityauditlog_claimant_biometric_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='e.g. GCB Bank, Ecobank Ghana, Stanbic Bank, Absa, Fidelity Bank', max_length=150)),
                ('branch_name', models.CharField(blank=True, help_text='e.g. High Street, Ring Road Central, Spintex', max_length=150, null=True)),
                ('account_number', models.CharField(db_index=True, help_text='Bank account number or IBAN', max_length=50)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current / Checking Account'), ('FIXED_DEPOSIT', 'Fixed Deposit Account'), ('FOREIGN_CURRENCY', 'Foreign Currency Account (FCA/FEA)'), ('TREASURY_CASH', 'Call / Treasury Account'), ('OTHER', 'Other Bank Account')], default='SAVINGS', max_length=30)),
                ('currency', models.CharField(choices=[('GHS', 'Ghanaian Cedi (GHS)'), ('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('EUR', 'Euro (EUR)')], default='GHS', max_length=10)),
                ('estimated_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Optional rough balance or deposit balance for executor tracking', max_digits=14, null=True)),
                ('document_proof', models.FileField(blank=True, help_text='Account statement, deposit certificate, or passbook copy', null=True, upload_to='bank_records/')),
                ('instructions', models.TextField(blank=True, help_text='Claim guidance or special instructions for family and executors', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_or_broker', models.CharField(help_text='Fund manager, issuing bank, or brokerage firm (e.g. Databank, EDC, CalBank Brokerage)', max_length=150)),
                ('investment_type', models.CharField(choices=[('TREASURY_BILL', 'Government of Ghana Treasury Bill (91/182/364-Day)'), ('MUTUAL_FUND', 'Mutual Fund / Collective Investment Scheme'), ('EQUITY_SHARES', 'Listed Equities / GSE Shares'), ('TIER3_PENSION', 'Tier-3 Provident / Voluntary Private Pension'), ('GOVT_BOND', 'Government / Corporate Bond'), ('OTHER', 'Other Investment Asset')], default='TREASURY_BILL', max_length=30)),
                ('portfolio_reference', models.CharField(db_index=True, help_text='CSD account number, investor ID, or mutual fund portfolio number', max_length=100)),
                ('title', models.CharField(help_text='e.g. Databank MFund, 182-Day GoG T-Bill, MTN Ghana Shares', max_length=255)),
                ('face_or_invested_value', models.DecimalField(blank=True, decimal_places=2, help_text='Initial investment amount or principal face value (GHS)', max_digits=14, null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='Maturity date if applicable (e.g. for T-Bills or fixed bonds)', null=True)),
                ('document_proof', models.FileField(blank=True, help_text='CSD statement, investment contract certificate, or purchase slip', null=True, upload_to='investment_proofs/')),
                ('notes', models.TextField(blank=True, help_text='Special instructions, rollover directives, or broker contacts', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Holding',
                'verbose_name_plural': 'Investment Holdings',
                'ordering': ['-created_at'],
            },
        ),
    ]
