# Generated by Django 6.0.1 on 2026-09-08 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_platformconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('STANDARD', 'Individual Custody'), ('SOVEREIGN', 'Sovereign Family Vault')], default='STANDARD', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('QUARTERLY', 'Quarterly Contribution'), ('ANNUALLY', 'Annual Contribution')], default='ANNUALLY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Current'), ('PAST_DUE', 'Past Due (Grace Period)'), ('EXPIRED', 'Expired / Locked'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_plan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_authorization_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
