# Generated by Django 6.0.1 on 2026-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='annual_subscription_fee',
            field=models.DecimalField(decimal_places=2, default=1200.0, help_text='Annual digital estate vault retainer fee (GHS)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='paystack_annual_plan_code',
            field=models.CharField(default='PLN_14xz26jx9j3gakp', help_text='Paystack Plan Code for Annual Retainer', max_length=100),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='paystack_quarterly_plan_code',
            field=models.CharField(default='PLN_1gba1fu8sg69ik0', help_text='Paystack Plan Code for Quarterly Retainer', max_length=100),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='quarterly_subscription_fee',
            field=models.DecimalField(decimal_places=2, default=450.0, help_text='Quarterly digital estate vault retainer fee (GHS)', max_digits=10),
        ),
    ]
