# Generated by Django 6.0.1 on 2026-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_platformconfiguration_annual_subscription_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_birth_city',
            field=models.CharField(blank=True, help_text='Where were you born?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_high_school_crush',
            field=models.CharField(blank=True, help_text='Who was your first high school crush?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_mother_maiden_name',
            field=models.CharField(blank=True, help_text="What is your mother's maiden name?", max_length=255, null=True),
        ),
    ]
