# Generated by Django 6.0.1 on 2026-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_customuser_security_birth_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
