# Generated by Django 6.0.1 on 2026-09-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_customuser_otp_created_at_customuser_phone_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='vault.policyrecord'),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
