# Generated by Django 6.0.1 on 2026-09-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_claimsecurityauditlog_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General Support'), ('POLICY_LINKING', 'Policy Linking & Sync'), ('CLAIMANT_VERIFY', 'Next-of-Kin Verification'), ('SUBSCRIPTION', 'Vault Protection Plans'), ('UNDERWRITER', 'Insurer Integration')], default='GENERAL', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New / Unread'), ('IN_REVIEW', 'In Desk Review'), ('RESOLVED', 'Resolved / Closed')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal desk notes regarding resolution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
