# Generated by Django 6.0.1 on 2026-09-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_contactinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimantaccessgrant',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='claimantaccessgrant',
            name='claimant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='claimantaccessgrant',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='claimantaccessgrant',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_claimant_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
