# Generated by Django 6.0.1 on 2026-09-12 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_alter_claimantaccessgrant_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Statutory identity verification question prompt', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active questions appear in citizen registration and setup forms')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering rank in dropdown selectors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(help_text='Case-insensitive verification string', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answered_by_users', to='vault.securityquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Answer',
                'verbose_name_plural': 'User Security Answers',
                'ordering': ['question__display_order', 'created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
