# Generated by Django 6.0.1 on 2026-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_securityquestion_usersecurityanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='required_security_questions',
            field=models.PositiveIntegerField(default=3, help_text='Number of security questions a citizen must select and answer during registration or setup (e.g. 3, 5, or 10).'),
        ),
    ]
