# Generated by Django 6.0.1 on 2026-09-12 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0019_platformconfiguration_required_security_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('GRANDPARENT', 'Grandparent'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse / Partner'), ('SIBLING', 'Sibling (Brother / Sister)'), ('CHILD', 'Child (Son / Daughter)'), ('GRANDCHILD', 'Grandchild'), ('OTHER', 'Other Relative')], max_length=30)),
                ('full_name', models.CharField(help_text='Full legal or ancestral name', max_length=255)),
                ('maiden_name', models.CharField(blank=True, help_text='Maiden name (if applicable)', max_length=150, null=True)),
                ('birth_year', models.CharField(blank=True, help_text='e.g. 1954, or exact birth date', max_length=50, null=True)),
                ('birth_place', models.CharField(blank=True, help_text='Town / City of birth (e.g. Kumasi, Mampong, Accra)', max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Portrait or vintage photograph', null=True, upload_to='family_tree/%Y/%m/')),
                ('bio_notes', models.TextField(blank=True, help_text='Biographical notes, ancestral clan, or memorable anecdotes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_emergency_contact', models.ForeignKey(blank=True, help_text='Link to existing statutory next-of-kin contact if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_tree_nodes', to='vault.emergencycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tree_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Tree Member',
                'verbose_name_plural': 'Family Tree Members',
                'ordering': ['relationship', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='MilestonePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Milestone title (e.g. First Car, First Kiss, Childhood Nickname)', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('FIRSTS', 'Firsts & Early Milestones'), ('FAMILY_LEGACY', 'Family Heritage & Lineage'), ('ACHIEVEMENTS', 'Achievements & Career'), ('TRIVIA', 'Personal Trivia & Favorites'), ('OTHER', 'Other Memories')], default='FIRSTS', max_length=30)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved & Live'), ('PENDING_REVIEW', 'Pending Admin Review'), ('REJECTED', 'Rejected / Ineligible')], default='APPROVED', help_text='Only APPROVED milestones appear for citizens to select on their dashboard.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle switch to hide or show without deleting.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering rank in dropdown selectors.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_by', models.ForeignKey(blank=True, help_text='Citizen who suggested this milestone (blank if created by administrator).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Prompt',
                'verbose_name_plural': 'Milestone Prompts',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CitizenMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_or_answer', models.TextField(help_text='Personal story, trivia details, or milestone narrative.')),
                ('photo', models.ImageField(blank=True, help_text='Memorable picture attached to this milestone.', null=True, upload_to='vault_memories/%Y/%m/')),
                ('approximate_year_or_era', models.CharField(blank=True, help_text='e.g. Circa 1994, Summer 2005, Class of 2010', max_length=100, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for administrative review if reported or prohibited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizen_memories', to='vault.milestoneprompt')),
            ],
            options={
                'verbose_name': 'Citizen Memory & Keepsake',
                'verbose_name_plural': 'Citizen Memories & Keepsakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
