# Generated by Django 6.0.1 on 2026-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_familymember_milestoneprompt_citizenmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paid_registration_fee',
            field=models.BooleanField(default=False, help_text='Designates whether the citizen has paid the one-time statutory registration fee.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_payment_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference for the one-time registration fee.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='One-time citizen vault registration fee charged via Paystack (GHS)', max_digits=10),
        ),
    ]
