# Generated by Django 6.0.1 on 2026-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_customuser_has_paid_registration_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='paystack_quarterly_plan_code',
        ),
        migrations.RemoveField(
            model_name='platformconfiguration',
            name='quarterly_subscription_fee',
        ),
        migrations.AlterField(
            model_name='platformconfiguration',
            name='annual_subscription_fee',
            field=models.DecimalField(decimal_places=2, default=120.0, help_text='Annual digital estate vault retainer fee (GHS)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformconfiguration',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='One-time statutory citizen vault registration fee charged via Paystack (GHS)', max_digits=10),
        ),
    ]
