# Generated by Django 6.0.1 on 2026-09-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_remove_platformconfiguration_paystack_quarterly_plan_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_assets_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Property, Land & Assets Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_banks_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Bank Accounts Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_family_tree_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Family Tree & Lineage Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_investments_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Investments & T-Bills Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_memories_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Memory Lane & Keepsakes Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_policies_enabled',
            field=models.BooleanField(default=True, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Insurance Policies Module'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='module_wills_enabled',
            field=models.BooleanField(default=False, help_text="Unchecking locks this module as 'Coming Soon' across home and dashboard.", verbose_name='Enable Digital Wills & Deeds Module'),
        ),
    ]
