# Generated by Django 6.0.1 on 2026-09-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecurityanswer',
            name='answer',
            field=models.CharField(help_text='Cryptographically salted one-way hash (PBKDF2/SHA256)', max_length=255),
        ),
    ]
