# Generated by Django 6.0.1 on 2026-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0025_alter_usersecurityanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='security_anti_inspect_enabled',
            field=models.BooleanField(default=True, help_text='Developer Master Toggle: When enabled, suppresses right-click menus, shortcuts (F12, Ctrl+Shift+I/J/C, Ctrl+U), and active debuggers site-wide. Uncheck to inspect elements during development and debugging.', verbose_name='Enable Anti-Inspect & DevTools Lockout'),
        ),
    ]
