# Generated by Django 6.0.1 on 2026-09-20 07:48

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_platformconfiguration_security_anti_inspect_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tracks consecutive invalid attempts to halt brute-force attacks.'),
        ),
        migrations.AlterField(
            model_name='assetrecord',
            name='document_proof',
            field=models.FileField(blank=True, null=True, upload_to=vault.models.secure_vault_upload_path),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='document_proof',
            field=models.FileField(blank=True, help_text='Account statement, deposit certificate, or passbook copy', null=True, upload_to=vault.models.secure_vault_upload_path),
        ),
        migrations.AlterField(
            model_name='estatedocument',
            name='document_file',
            field=models.FileField(upload_to=vault.models.secure_vault_upload_path),
        ),
        migrations.AlterField(
            model_name='investmentholding',
            name='document_proof',
            field=models.FileField(blank=True, help_text='CSD statement, investment contract certificate, or purchase slip', null=True, upload_to=vault.models.secure_vault_upload_path),
        ),
    ]
