# Generated by Django 6.0.1 on 2026-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0027_customuser_otp_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimantaccessgrant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this claimant docket remains active and accessible.'),
        ),
    ]
