# Generated by Django 6.0.1 on 2026-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_alter_claimantaccessgrant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='security_dom_poisoning_enabled',
            field=models.BooleanField(default=True, help_text='When active, wipes the DOM tree clean upon inspection and floods the Elements tab with simulated kernel panics and forensic honeypot memory dumps.', verbose_name='Enable Hardcore DOM Memory Poisoning'),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='security_poison_density',
            field=models.PositiveIntegerField(default=30, help_text='Number of simulated hex memory sectors, register dumps, and audit traps to inject.', verbose_name='Poison Decoy Density'),
        ),
    ]
