# Generated by Django 6.0.1 on 2026-09-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0029_platformconfiguration_security_dom_poisoning_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active & In Good Standing'), ('SUSPENDED', 'Suspended (Temporary Review / Lock)'), ('TERMINATED', 'Terminated (Permanent Revocation / Ban)')], db_index=True, default='ACTIVE', help_text='Administrative access clearance state: Active, Suspended, or Terminated.', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for administrative suspension or termination displayed to the user upon login.', null=True),
        ),
    ]
