# Generated by Django 6.0.1 on 2026-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0030_customuser_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfiguration',
            name='annual_subscription_fee',
            field=models.DecimalField(decimal_places=2, default=1200.0, help_text='Annual digital estate vault retainer fee (GHS)', max_digits=10),
        ),
    ]
