# Generated by Django 6.0.1 on 2026-09-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0031_alter_platformconfiguration_annual_subscription_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfiguration',
            name='required_security_questions',
            field=models.PositiveIntegerField(default=20, help_text='Number of security questions a citizen must select and answer during registration or setup (e.g. 3, 5, 10, or 20).'),
        ),
    ]
