# Generated by Django 6.0.1 on 2026-09-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0032_alter_platformconfiguration_required_security_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityquestion',
            options={'ordering': ['tier', 'display_order', 'id'], 'verbose_name': 'Security Question', 'verbose_name_plural': 'Security Questions'},
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='tier',
            field=models.CharField(choices=[('TIER_1', 'Tier 1: Identity & Origins'), ('TIER_2', 'Tier 2: Family & Ancestral Lineage'), ('TIER_3', 'Tier 3: Education & Formative Years'), ('TIER_4', 'Tier 4: Personal Lore & Traditions')], db_index=True, default='TIER_1', help_text='Statutory security tier classification', max_length=20),
        ),
    ]
