# Generated by Django 6.0.1 on 2026-09-29 00:11

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0033_alter_securityquestion_options_securityquestion_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimantaccessgrant',
            name='death_certificate',
            field=models.FileField(blank=True, help_text='Official scanned statutory death certificate or certificate of death extract.', null=True, upload_to=vault.models.secure_vault_upload_path),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='death_certificate',
            field=models.FileField(blank=True, help_text='Uploaded statutory death certificate captured during forensic intake audit.', null=True, upload_to=vault.models.secure_vault_upload_path),
        ),
    ]
