# Generated by Django 6.0.1 on 2026-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0034_claimantaccessgrant_death_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='cancelled_stage',
            field=models.CharField(blank=True, help_text='Stage at which the user cancelled or exited the verification funnel.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='custody_ghana_card_captured',
            field=models.CharField(blank=True, help_text='Policyholder Ghana Card ID entered by claimant during custody check.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claimsecurityauditlog',
            name='sq_answers_captured',
            field=models.TextField(blank=True, help_text='JSON payload of security questions and answers submitted during intake.', null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='claimant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='claimant_ghana_card',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='claimant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='claimant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='relationship_stated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claimsecurityauditlog',
            name='status',
            field=models.CharField(choices=[('VERIFIED_MATCH', 'Verified Next-of-Kin Match'), ('UNMATCHED_FLAGGED', 'Unmatched Identity - Audit Flagged'), ('ABANDONED_EXIT', 'Abandoned / Cancelled Early'), ('INVESTIGATION_PENDING', 'Under Desk Fraud Review')], default='UNMATCHED_FLAGGED', max_length=30),
        ),
    ]
