# Generated by Django 6.0.1 on 2026-09-30 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0035_claimsecurityauditlog_cancelled_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultModuleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(choices=[('memories', 'Folder 02: Memory Lane & Keepsakes'), ('family_tree', 'Folder 03: Family Tree & Lineage'), ('bank_accounts', 'Folder 04: Commercial Bank Accounts'), ('investments', 'Folder 05: Investments & T-Bills'), ('wills_deeds', 'Folder 06: Digital Wills & Deeds'), ('properties_assets', 'Folder 07: Properties & Physical Assets')], db_index=True, max_length=50, unique=True)),
                ('folder_number', models.CharField(help_text="e.g. '02', '03', '04', '05', '06', '07'", max_length=10)),
                ('description', models.TextField(help_text='Marketing and discovery summary displayed on pricing page.')),
                ('annual_price_ghs', models.DecimalField(decimal_places=2, default=250.0, help_text='Recurring annual add-on fee in GHS', max_digits=10)),
                ('paystack_plan_code', models.CharField(blank=True, help_text='Paystack Plan Code for this specific recurring add-on (e.g. PLN_xxxx)', max_length=100, null=True)),
                ('is_released', models.BooleanField(default=False, help_text="False = Display as 'Coming Soon' / Waitlist. True = Unlocked for active purchase.")),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Vault Module Catalog',
                'verbose_name_plural': 'Vault Module Catalogs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Current'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired / Locked'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscribers', to='vault.vaultmodulecatalog')),
            ],
            options={
                'verbose_name': 'User Module Subscription',
                'verbose_name_plural': 'User Module Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
